# -*- coding: utf-8 -*-
"""stock_market_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a8bDvzUCE9zpf9jCQo9tNulpSj3va9Hi
"""

import pandas as pd
import yfinance as yf
import datetime
from datetime import date, timedelta
today = date.today()

d1 = today.strftime("%Y-%m-%d")
end_date = d1
d2 = date.today() - timedelta(days=360)
d2 = d2.strftime("%Y-%m-%d")
start_date = d2

data = yf.download('AAPL',
                      start=start_date,
                      end=end_date,
                      progress=False)
print(data.head())

data["Date"] = data.index
data = data[["Date", "Open", "High",
             "Low", "Close", "Volume"]]
data.reset_index(drop=True, inplace=True)
print(data.head())

import matplotlib.pyplot as plt

# Plot the closing price trend
plt.figure(figsize=(10, 6))
plt.plot(data['Date'], data['Close'], label='Closing Price', color='blue')
plt.title('AAPL Closing Price Over Time')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.legend()
plt.grid()
plt.show()

# Calculate moving averages
data['SMA_50'] = data['Close'].rolling(window=50).mean()
data['SMA_200'] = data['Close'].rolling(window=200).mean()

# Plot SMA with closing prices
plt.figure(figsize=(12, 6))
plt.plot(data['Date'], data['Close'], label='Closing Price', color='blue')
plt.plot(data['Date'], data['SMA_50'], label='50-Day SMA', color='green')
plt.plot(data['Date'], data['SMA_200'], label='200-Day SMA', color='red')
plt.title('AAPL Stock Price with Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.legend()
plt.grid()
plt.show()

# Calculate daily returns
data['Daily Return'] = data['Close'].pct_change()

# Plot daily returns
plt.figure(figsize=(10, 6))
plt.plot(data['Date'], data['Daily Return'], label='Daily Return', color='orange')
plt.title('AAPL Daily Returns Over Time')
plt.xlabel('Date')
plt.ylabel('Daily Return')
plt.axhline(0, color='black', linestyle='--', linewidth=0.7)
plt.legend()
plt.grid()
plt.show()

# Calculate Bollinger Bands
data['20 Day MA'] = data['Close'].rolling(window=20).mean()
data['20 Day STD'] = data['Close'].rolling(window=20).std()
data['Upper Band'] = data['20 Day MA'] + (2 * data['20 Day STD'])
data['Lower Band'] = data['20 Day MA'] - (2 * data['20 Day STD'])

# Plot Bollinger Bands
plt.figure(figsize=(12, 6))
plt.plot(data['Date'], data['Close'], label='Closing Price', color='blue')
plt.plot(data['Date'], data['Upper Band'], label='Upper Band', color='green', linestyle='--')
plt.plot(data['Date'], data['Lower Band'], label='Lower Band', color='red', linestyle='--')
plt.fill_between(data['Date'], data['Upper Band'], data['Lower Band'], color='gray', alpha=0.1)
plt.title('AAPL Stock Price with Bollinger Bands')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.legend()
plt.grid()
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

# Prepare data for prediction (using only closing price and index as a feature)
data['Days'] = np.arange(len(data))
X = data[['Days']]
y = data['Close']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict
data['Predicted Close'] = model.predict(X)

# Plot predictions
plt.figure(figsize=(12, 6))
plt.plot(data['Date'], data['Close'], label='Actual Closing Price', color='blue')
plt.plot(data['Date'], data['Predicted Close'], label='Predicted Closing Price', color='orange')
plt.title('AAPL Stock Price Prediction')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.legend()
plt.grid()
plt.show()

tickers = ['AAPL', 'MSFT', 'GOOG']
stock_data = {}

for ticker in tickers:
    stock_data[ticker] = yf.download(ticker, start=start_date, end=end_date, progress=False)
    stock_data[ticker]["Date"] = stock_data[ticker].index
    stock_data[ticker].reset_index(drop=True, inplace=True)

# Example: Visualize closing price
plt.figure(figsize=(10, 6))
plt.plot(stock_data['MSFT']['Date'], stock_data['MSFT']['Close'], label='MSFT Closing Price', color='purple')
plt.title('MSFT Closing Price Over Time')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.legend()
plt.grid()
plt.show()

pip install fpdf

from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Stock Price Analysis Report', 0, 1, 'C')

    def add_content(self, text):
        self.set_font('Arial', '', 12)
        self.multi_cell(0, 10, text)

pdf = PDF()
pdf.add_page()
pdf.add_content(f"Stock Analysis for AAPL from {start_date} to {end_date}")
pdf.add_content(f"\nSummary Statistics:\n{data[['Close', 'Volume']].describe()}")
pdf.output('Stock_Analysis_Report.pdf')

# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# from sklearn.preprocessing import MinMaxScaler
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, LSTM

# # Use only the 'Close' column for prediction
# data_close = data[['Close']].values

# # Scale the data to the range [0, 1] for better performance with LSTM
# scaler = MinMaxScaler(feature_range=(0, 1))
# scaled_data = scaler.fit_transform(data_close)

# # Create training data
# train_size = int(len(scaled_data) * 0.8)  # 80% for training
# train_data = scaled_data[:train_size]
# test_data = scaled_data[train_size:]

# #print(test_data.shape)

# # Create sequences of 60 days as input and the next day as output
# def create_sequences(data, sequence_length=30):
#     x, y = [], []
#     for i in range(sequence_length, len(data)):
#         x.append(data[i-sequence_length:i, 0])  # Last 60 days as input
#         y.append(data[i, 0])                   # Next day's closing price as output
#     return np.array(x), np.array(y)

# sequence_length = 30
# x_train, y_train = create_sequences(train_data, sequence_length)
# x_test, y_test = create_sequences(test_data, sequence_length)

# # Reshape data for LSTM [samples, time_steps, features]
# x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
# x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))

# # Build the LSTM model
# model = Sequential([
#     LSTM(50, return_sequences=True, input_shape=(x_train.shape[1], 1)),
#     LSTM(50, return_sequences=False),
#     Dense(25),
#     Dense(1)
# ])

# # Compile the model
# model.compile(optimizer='adam', loss='mean_squared_error')

# # Train the model
# model.fit(x_train, y_train, batch_size=32, epochs=10)

# # Predict on training and testing data
# train_predictions = model.predict(x_train)
# test_predictions = model.predict(x_test)

# # Reverse scaling
# train_predictions = scaler.inverse_transform(train_predictions)
# y_train = scaler.inverse_transform(y_train.reshape(-1, 1))
# test_predictions = scaler.inverse_transform(test_predictions)
# y_test = scaler.inverse_transform(y_test.reshape(-1, 1))

# print(train_range.shape, test_range.shape, data_close[train_size:].shape, test_predictions.shape)

# # Ensure all dimensions match
# data_close_test = data_close[train_size:train_size + len(test_range)].flatten()  # Match test_range length
# test_predictions = test_predictions.flatten()  # Flatten predictions to 1D

# # Plot
# plt.figure(figsize=(14, 7))
# plt.plot(train_range, data_close[:train_size], label='Training Data', color='blue')
# plt.plot(test_range, data_close_test, label='Testing Data', color='green')
# plt.plot(test_range, test_predictions, label='LSTM Predictions', color='red')
# plt.title('Stock Price Prediction with LSTM')
# plt.legend()
# plt.show()


# model.save('lstm_stock_model.h5')

# print(test_range)
# print(test_predictions)

# print(test_predictions[:5], data_close[train_size:train_size+5])

# pdf.add_content("\nLSTM Stock Price Prediction")
# pdf.add_content(f"Predicted vs Actual Stock Prices for Testing Data")
# # You can include further description or visualizations here
# pdf.output('Stock_Analysis_Report_With_LSTM.pdf')